controller_list:
  - name: fake_edo_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_eef_group_controller
    joints:
      - joint_6